### ISSUE TITLE
Affichage des entités annotées au survol

### ISSUE THREAD

**Issue by MrGecko** [MrGecko/lettres-vue#11]
Les entités nommées (personnes, lieux) sont actuellement étiquetées  manuellement par des utilisateurs au sein de l’éditeur de texte riche QuillJS à l’aide des balises _persName_ et _placeName_.
L’application lie correctement un identifiant à une portion de texte mais ne crée pour le moment qu’un lien html factice qui ne permet, ni d’identifier facilement la cible du lien (nom de la personne ou du lieu), ni d’accéder à la notice d’autorité de l’entité concernée.

**Objectif :** concevoir un moyen d’afficher un composant au survol des entités permettant d'afficher :
- Des informations complémentaires concernant l'entité
- un lien cliquable menant à la page de notice (tbd) de l’entité
- En mode édition (utilisateur connecté), des boutons d’action supplémentaires :
	- supprimer la liaison entre la portion de texte et l'entité
	- ouvrir le formulaire d’édition de l’entité

**Attention**, l’utilisation de popup/tooltip via l’insertion de balises autour des entités ne doit pas entrer en conflit avec QuillJS. De plus, ces balises ne doivent pas être sauvegardées.

**Comment by MrGecko** [comment]
cf. l'issue Adele similaire [https://github.com/chartes/adele-vue/issues/34](https://github.com/chartes/adele-vue/issues/34)

**Comment by vicpsl** [comment]
Implémentation effectuée comme suit : 

- Des informations complémentaires concernant l'entité : **non implémenté**.
- Lien cliquable menant à la page de notice (tbd) de l’entité : **liens href**
- En mode édition (utilisateur connecté), des boutons d’action supplémentaires :
	- supprimer la liaison entre la portion de texte et l'entité : **la sélection d'un persName / placeName et l'ouverture du pop-up d'édition permet désormais la suppression du lien** : 
	  - dans la section concernée (un lien entre la lettre et l'entité dans une autre section est conservée)
	  - l'entité en elle-même n'est pas supprimée
	- ouvrir le formulaire d’édition de l’entité : **la sélection d'un persName / placeName et l'ouverture du pop-up d'édition permet désormais l'édition du lien**


via les commits : 
https://github.com/chartes/lettres-vue/commit/fe635d72550016c25bd627f65de2f7b6b53d9954  
https://github.com/chartes/lettres-vue/commit/8ad2aa323d930677c48550e1486786a2cce5483d  
https://github.com/chartes/lettres-vue/commit/a47e545d15f8b05ea43ee709000b30cbdccde004
