### ISSUE TITLE
Edition du document : erreur lors de la suppression d'un témoin

### ISSUE THREAD

**Issue by vicpsl** [MrGecko/lettres-vue#115]
Edition du document : erreur lors de la suppression d'un témoin (icône bin sur le témoin) :

![image](https://github.com/chartes/lettres-vue/assets/92852428/2c382ccd-86c0-46d1-a617-d3ec2b13e066)

Revoir l'enchaînement des fonctions dans "async deleteWitness(witness)" du composant WitnessList.vue : 

La suppression du témoin a lieu, l'ordre des témoins à la suite de cette suppression est correctement remanié, enfin le changement est ajouté au Changelog convenablement.

Néanmoins, lors du rechargement du document (appelé dans document/index.js : reorderWitnesses), une erreur 405 se produit : 
Réponse de la console :
![image](https://github.com/chartes/lettres-vue/assets/92852428/c894f964-9d34-4b98-9795-bcb352efbd87)
Log du backend : 
![image](https://github.com/chartes/lettres-vue/assets/92852428/9124c7a7-4453-4756-b56d-0aad424ddbdb)

Merci

**Comment by fbessou** [comment]
Bonjour Victor,

Cette issue était particulièrement tordue !
Le problème survenait uniquement sur firefox et après soumission des témoins. J'ai cru pendant un moment que c'était la faute à firefox ou à la bibliothèque Axios, qu'on utilise pour faire nos requête.
Mais apparemment, c'est werkzeug (le serveur wsgi utilisé par flask) qui dans la version qu'on utilisait jusqu'à présent ET en mode multi-thread fusionnait des requêtes HTTP dans certaines condition.
Du coup Flask se retrouvait à devoir traité une requête avec comme méthode la chaine de charactère "{"data":{"id":1,"type":"witness"}}GET".

En utilisant un autre serveur wsgi on a pas ce problème, donc je suppose qu'en prod il ne survient pas. J'ai changé la version de werkzeug dans le requirements.txt et le bug à l'air d'être résolu.
Il faudra voir si il y a d'autres paquets qu'on peut mettre à jour.
