### ISSUE TITLE
Suppression d'un document

### ISSUE THREAD

**Issue by MrGecko** [MrGecko/lettres-vue#12]
La suppression d’un document doit être implémentée puis intégrée côté frontend sous la forme d’un composant (un bouton) intégrable à différents endroits de l’interface.

- Il faut être connecté avec le role `admin` pour avoir le droit de supprimer un document
- La suppression d’un document doit entrainer la suppression des dépendances associées (delete on cascade) : bookmarks, witnesses, changelog, notes, images

**Comment by vicpsl** [comment]
Bonjour Julien,

étant donné que nous avons effectué le merge des développements du bouton Suppression d'un document, pourrait-on clore cette issue ?

Merci
Victor

**Comment by vicpsl** [comment]
Closed by #19

**Comment by vicpsl** [comment]
Closed by #19
