### ISSUE TITLE
Gérer les collections - Ajout/Edition d'une collection

### ISSUE THREAD

**Issue by vicpsl** [MrGecko/lettres-vue#24]
Rappel : l'ajout et l'édition d'une collection est l'un des développements nécessaires discutés à l'issue #14.

### Développements nécessaires :

- [ ] construire le formulaire de création / édition de (sous-)collections.
 - **pour les seuls admin**.
- le formulaire doit être éditable par tout user **admin**, comme la mise à jour de la description.
- le formulaire consiste en : voir https://github.com/chartes/lettres-vue/issues/14#issuecomment-1315498200.
  - éléments propres à la collection : 
    - titre (obligatoire, champ de texte)
    - "administrateur" (obligatoire, **sélection d'un administrateur**)
    NB : il serait nécessaire de pouvoir sélectionner / éditer l'administrateur associé à une (sous-)collection car c'est celui qui apparaîtra en tant que "Curated by ..." sur la page. Voir le comment : https://github.com/chartes/lettres-vue/issues/14#issuecomment-1331319239
    - description (optionnel, champ de texte)
    - NB : les dates associées à la (sous-)collection créée ne sont pas éditables (calculées à partir des documents associés). En l'absence de documents à la création, les attributs date_min et date_max = leur valeur défaut et gérés côté Front pour afficher "na" ou "Non renseigné".

- [ ] gérer relations parents/enfants d'une nouvelle collection (sur la base de la maquette) : 
NB : voir https://github.com/chartes/lettres-vue/issues/14#issuecomment-1315546100, https://github.com/chartes/lettres-vue/issues/14#issuecomment-1318350654.
- **page /collections/** : 
   - une collection racine est ajoutée à partir de l'URL /collections seulement (image 1 de la pj)
- **page /collections/id** : 
   - une sous-collection est ajoutée à partir l'URL /collections/id de son parent (image 3 de la pj)

- [ ] redirection à l'issue de la création :
NB : le comment https://github.com/chartes/lettres-vue/issues/14#issuecomment-1331313493
- Renvoyer vers la collection nouvellement créée

**Comment by vicpsl** [comment]
Carine,

un fix est encore nécessaire sur la partie backend : 

1. il est possible de passer une chaîne title vide directement par l'API avec : 
curl -X PATCH   http://localhost:5004/api/1.0/collections/55  -H 'Accept: application/vnd.api+json'   -H 'Content-Type: application/json'   -H 'cache-control: no-cache'   -H 'Authorization: **Bearer_id(admin)**'  -d '{"data":{"type":"collection","id":55,"attributes":{**title":""**,"description"::"Test suppression titre en CURL","admin_id":4}}}'
2. la mise à jour du title à ```null``` directement par l'API avec :
curl -X PATCH   http://localhost:5004/api/1.0/collections/55  -H 'Accept: application/vnd.api+json'   -H 'Content-Type: application/json'   -H 'cache-control: no-cache'   -H 'Authorization: **Bearer_id(admin)**'  -d '{"data":{"type":"collection","id":55,"attributes":{"title":null,"description":"Test titre null en CURL","admin_id":4}}}' renvoie bien une erreur 400 comme prévu mais sans message explicite : à rajouter dans la liste des messages ? "Hint: title is missing/cannot be null"

Closed by https://github.com/chartes/lettres-app/pull/87.

Merci
Victor

**Comment by carinedengler** [comment]
Salut Victor,

je vais regarder cela.

**Comment by vicpsl** [comment]
Closed by Editorial dev #20  (which included #33 and #37  ).
