### ISSUE TITLE
Gérer les collections - Arbre des collections sur la page /collections/ (et les résultats de filtres)

### ISSUE THREAD

**Issue by vicpsl** [MrGecko/lettres-vue#26]
Rappel : la présentation de la structure d'une collection est l'un des développements nécessaires discutés à l'issue #14.

### Développements nécessaires :
- [ ] bouton « Parcourir la collection »
  - pour tous les users connectés (quel que soit leur statut) et non connectés
- [ ] ce bouton affiche une arborescence simplifiée de la collection : 
  - Titre, nombre de lettres
  - depuis le niveau racine
  - repliée par défaut
  - voir notre illustration n°2 à https://github.com/chartes/lettres-vue/issues/14#issuecomment-1315498200. NB : Même arbre à afficher sur une liste de résultat comme celle de l'illustration n°5 (e.g. depuis la racine, pour chaque résultat).

**Comment by fbessou** [comment]
Je propose de renommer cette issue pour enlever " et les résultats de filtres" étant donné que cette fonctionnalité est traitée dans #32.
