### ISSUE TITLE
Gérer les collections - Editer les liens des documents vers les collections sur la page /documents/id

### ISSUE THREAD

**Issue by vicpsl** [MrGecko/lettres-vue#28]
Rappel : l'ajout de lettres à une collection est l'un des développements nécessaires discutés à l'issue #14.

### Développements nécessaires :
- pour les users connectés admin et contributeurs
- l'ajout d'un document à une collection met à jour la liste des collections auxquelles il est rattaché dans la section "Collections" de sa page /documents/id : 
![image](https://user-images.githubusercontent.com/92852428/206171149-33550916-4fa7-4d88-a8c5-a12d972cf737.png)

- [ ] ajouter à la page /documents/id/ (section "Collections") un sélecteur de collection(s)
  - liste déroulante (none|toutes les collections disponibles, à plat)
  - pouvoir sélectionner plusieurs (sous-)collections

**Comment by fbessou** [comment]
On utilisera un champ autocomplete. À la sélection d'une collection, celle-ci est reliée.
À côté de chaque collection déjà reliée, on ajoutera un bouton pour permettant de retirer le document de la collection.

Je fais une première tentative ou la complétion se fait uniquement sur le nom de la collection. Peut-être faudra-t-il la faire sur le chemin complet de la collection pour éviter les ambiguïtés.
