### ISSUE TITLE
Implémenter les suggestions (page recherche avancée)

### ISSUE THREAD

**Issue by vicpsl** [MrGecko/lettres-vue#44]
Implémenter les suggestions (page recherche avancée) : 

![image](https://github.com/chartes/lettres-vue/assets/92852428/a5bfcbd2-3c12-44e6-ad20-c02bd3bc60f4)

**Comment by ethieblin** [comment]
Les suggestions sont-elles:
1. les URL des pages des entités "lieux, personnes, etc." cités dans les documents ?
ou
2. un raccourci pour les facettes : un clic sur "Montpellier" ajoute le filtre "Montpellier" sur les lieux dans la recherche ?

**Comment by vicpsl** [comment]
Les suggestions sont bien un raccourci pour les facettes, avec une petite précision :
- un clic sur "**_DES_** Montpellier" ajoute le filtre "Montpellier" en tant que **_lieu de destination_** dans la recherche ;
- un clic sur "**_CIT_** Venise" ajoute le filtre "Venise" en tant que **_lieu cité_** dans la recherche.
Merci

**Comment by vicpsl** [comment]
Bonjour,
l'implémentation des suggestions a été mergé via la PR #103. 

En revanche, les éléments suivants doivent être corrigés : 

- [x] il convient de corriger le compteur des suggestions de collections qui est basé sur l'attribut publishedCount quel que soit le statut de connection (voir composant SuggestionsBox.vue, fonction getCollectionsToSuggest() : "count: item.publishedCount". Ce compteur doit refléter le **nombre de documents associés au tag dans le résultat de recherche courant**.

- [x] L'ouverture de l'onglet de recherche avancée est suivi de deux fois la même requête API http://localhost:5004/lettres/api/1.0/search?query=&searchtype=paratext&highlight=false&page[size]=30&page[number]=1&without-relationships&sort=creation

Le CSS doit être corrigé afin de rétablir le fonctionnement Responsive précédent : 
- [x] La recherche dans une facette se situe en arrière plan du bandeau principal de Recherche avancée (voir ci-dessous, on distingue le bas des lettres Expéditeurs en rose entre les facettes Personnes et Lieux), au lieu d'être en avant plan

**Branche suggestion incorrecte :**
<img src="https://github.com/chartes/lettres-vue/assets/92852428/763e5472-8a7d-49d5-8908-8c6fadb509e1" width="25%" height="25%" />

**Branche dev correcte :**

<img src="https://github.com/chartes/lettres-vue/assets/92852428/6550b512-3cea-4081-bc67-4e30c769cb6f" width="25%" height="25%" />

Merci

**Comment by vicpsl** [comment]
Le premier point (compteur des suggestions de collection) est corrigé par les commits a0b26fa et a0b26fa.

**Comment by vicpsl** [comment]
Résolu par les PR #108 et #109.
