### ISSUE TITLE
Ajout d’un prev/next entre les lettres d’une même collection

### ISSUE THREAD

**Issue by architexte** [MrGecko/lettres-vue#62]
Pouvoir feuilleter (prev/next) les lettres **d’une même collection** : pouvoir éditer la lettre précédente / suivante.

**Comment by vicpsl** [comment]
La navigation entre lettres (mais pas au sein d'une collection) a été implementée.

Bug à corriger pour gérer le préfixe de l'app (/lettres/).

**Comment by vicpsl** [comment]
Fixed dans la MAJ du 15/05/2023, commit : https://github.com/chartes/lettres-vue/commit/c31946c0b9fa747a5d544e6a58aada6fd09b3d1f
