### ISSUE TITLE
Bug à la saisie d’une numérotation au début du premier paragraphe

### ISSUE THREAD

**Issue by architexte** [MrGecko/lettres-vue#63]
> le champ "analyse" plante lorsque je tape un chiffre suivi d'un point et d'un espace. Ex: si je tape "1. ", la page plante.

Bug Quill : la page plante (!) quand on saisit un chiffre suivi d’un point (`^[0-9]\.`) au début du premier paragraphe d’un champ.

**Comment by MrGecko** [comment]
Aussi, Le numéro de paragraphe doit être visible à la fois en édition et en consultation

**Comment by vicpsl** [comment]
Le problème est résolu en désactivant les listes par défaut de Quill : 

Ajout d'un keybord binding dans LettresQuill.js pour désactiver le défaut.

'list autofill': {
  prefix: /^\s*()$/
}

![image](https://github.com/chartes/lettres-vue/assets/92852428/91f7279c-688d-4239-9379-291effd7c9a7)
